from __future__ import annotations

from pprint import pformat

from app.models.pipeline import PipelineExportRequest, PipelineStep
from app.operators.registry import get_operator

NOOP_TYPES = {"basic_readimage", "basic_writeimage", "border_for_all", "border_each_side"}


def export_pipeline_to_python(request: PipelineExportRequest) -> str:
    _validate_pipeline(request.pipeline)

    pipeline_literal = pformat(
        [{"type": step.type, "params": step.params} for step in request.pipeline],
        width=100,
        sort_dicts=True,
    )
    step_comments = "\n".join(_build_step_comment(index, step) for index, step in enumerate(request.pipeline, start=1))

    return "\n".join(
        [
            '"""Generated by ImageLab.\n\nRun this script from the imagelab-backend directory so the ImageLab operators\ncan be imported correctly. You can override the default paths via CLI:\n    python pipeline_export.py --input path/to/input.png --output path/to/output.png\n"""',
            "",
            "from __future__ import annotations",
            "",
            "import argparse",
            "from pathlib import Path",
            "from typing import Any",
            "",
            "import cv2",
            "import numpy as np",
            "",
            "from app.operators.registry import get_operator",
            "",
            f"DEFAULT_INPUT_PATH = {request.input_path!r}",
            f"DEFAULT_OUTPUT_PATH = {request.output_path!r}",
            f"NOOP_TYPES = {repr(NOOP_TYPES)}",
            "",
            "# Exported pipeline steps:",
            step_comments,
            "PIPELINE: list[dict[str, Any]] = " + pipeline_literal,
            "",
            "",
            "def load_image(path: str) -> np.ndarray:",
            "    image = cv2.imread(path, cv2.IMREAD_UNCHANGED)",
            "    if image is None:",
            "        raise FileNotFoundError(f\"Could not read input image: {path}\")",
            "    return image",
            "",
            "",
            "def run_pipeline(image: np.ndarray) -> np.ndarray:",
            "    for step_index, step in enumerate(PIPELINE, start=1):",
            "        step_type = str(step[\"type\"])",
            "        if step_type in NOOP_TYPES:",
            "            continue",
            "",
            "        operator_cls = get_operator(step_type)",
            "        if operator_cls is None:",
            "            raise ValueError(f\"Unsupported operator at step {step_index}: {step_type}\")",
            "",
            "        params = dict(step.get(\"params\", {}))",
            "        operator = operator_cls(params)",
            "        image = operator.compute(image)",
            "",
            "    return image",
            "",
            "",
            "def save_image(path: str, image: np.ndarray) -> None:",
            "    target = Path(path)",
            "    if target.parent != Path(\".\"):",
            "        target.parent.mkdir(parents=True, exist_ok=True)",
            "    if not cv2.imwrite(str(target), image):",
            "        raise RuntimeError(f\"Failed to save output image: {target}\")",
            "",
            "",
            "def build_parser() -> argparse.ArgumentParser:",
            "    parser = argparse.ArgumentParser(description=\"Run an ImageLab pipeline export.\")",
            "    parser.add_argument(\"--input\", default=DEFAULT_INPUT_PATH, help=\"Path to the input image\")",
            "    parser.add_argument(\"--output\", default=DEFAULT_OUTPUT_PATH, help=\"Path to save the processed image\")",
            "    return parser",
            "",
            "",
            "def main() -> int:",
            "    args = build_parser().parse_args()",
            "    image = load_image(args.input)",
            "    result = run_pipeline(image)",
            "    save_image(args.output, result)",
            "    print(f\"Saved processed image to {args.output}\")",
            "    return 0",
            "",
            "",
            "if __name__ == \"__main__\":",
            "    raise SystemExit(main())",
            "",
        ]
    )


def _validate_pipeline(pipeline: list[PipelineStep]) -> None:
    for index, step in enumerate(pipeline, start=1):
        if step.type in NOOP_TYPES:
            continue
        if get_operator(step.type) is None:
            raise ValueError(f"Unknown operator '{step.type}' at step {index}")


def _build_step_comment(index: int, step: PipelineStep) -> str:
    if step.type == "basic_readimage":
        return f"# {index}. Read image from --input"
    if step.type == "basic_writeimage":
        return f"# {index}. Save final image to --output"

    operator_cls = get_operator(step.type)
    display_name = operator_cls.__name__ if operator_cls is not None else step.type
    if step.params:
        return f"# {index}. {display_name} with params {pformat(step.params, sort_dicts=True)}"
    return f"# {index}. {display_name}"
