"""Add pipeline versioning tables

Revision ID: b323f95e8c19
Revises:
Create Date: 2026-06-16 18:09:05.459361

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b323f95e8c19"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_id"), "pipeline", ["id"], unique=False)
    op.create_table(
        "pipeline_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("workspace_json", sa.JSON(), nullable=False),
        sa.Column("pipeline_json", sa.JSON(), nullable=False),
        sa.Column("change_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pipeline_id", "version_number", name="uq_pipeline_id_version_number"),
    )
    op.create_index(op.f("ix_pipeline_version_id"), "pipeline_version", ["id"], unique=False)
    op.create_table(
        "pipeline_shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_version_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("permission", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipeline.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_version_id"], ["pipeline_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_shares_id"), "pipeline_shares", ["id"], unique=False)
    op.create_index(op.f("ix_pipeline_shares_token_hash"), "pipeline_shares", ["token_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_shares_token_hash"), table_name="pipeline_shares")
    op.drop_index(op.f("ix_pipeline_shares_id"), table_name="pipeline_shares")
    op.drop_table("pipeline_shares")
    op.drop_index(op.f("ix_pipeline_version_id"), table_name="pipeline_version")
    op.drop_table("pipeline_version")
    op.drop_index(op.f("ix_pipeline_id"), table_name="pipeline")
    op.drop_table("pipeline")
    # ### end Alembic commands ###
